# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: syncflow
    MINIO_ROOT_PASSWORD: syncflow-admin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - syncflow-data1-1:/data1
      - syncflow-data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - syncflow-data2-1:/data1
      - syncflow-data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - syncflow-data3-1:/data1
      - syncflow-data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - syncflow-data4-1:/data1
      - syncflow-data4-2:/data2
  
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

volumes:
  syncflow-data1-1:
  syncflow-data1-2:
  syncflow-data2-1:
  syncflow-data2-2:
  syncflow-data3-1:
  syncflow-data3-2:
  syncflow-data4-1:
  syncflow-data4-2: